name: Copy Usman.txt File

on:
  push:
    branches:
      - main

jobs:
  copy-file:
    runs-on: self-hosted
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Create Usman.txt File
      run: echo "my name is Usman" > usman.txt

    - name: Copy File to Local Machine
      run: cp usman.txt /home/ci-cd
